services:
    Controller.PutUserController:
        class: ../../controllers/user/PutUserController
        arguments: ['@UseCase.RegisterUser']
    
    UseCase.RegisterUser:
        class: ../../../context/user/application/RegistrerUser
        arguments: ['@Repository.MongoUserRepository']

    Controller.GetUserController:
        class: ../../controllers/user/GetUserController
        arguments: ['@UseCase.GetterUser']
    
    UseCase.GetterUser:
        class: ../../../context/user/application/GetterUser
        arguments: ['@Repository.MongoUserRepository']

    Repository.MongoUserRepository:
        class: ../../../context/user/infractucture/MongoUserRepository
        arguments: ['@ConnectionManager']


